CREATE ROLE parking LOGIN
ENCRYPTED PASSWORD 'md57cd57ed1f02e46dfd072a8909dbaebf2'
NOSUPERUSER INHERIT NOCREATEDB NOCREATEROLE NOREPLICATION;

CREATE DATABASE parking
WITH OWNER = parking
ENCODING = 'UTF8'
TABLESPACE = pg_default
LC_COLLATE = 'en_US.UTF-8'
LC_CTYPE = 'en_US.UTF-8'
CONNECTION LIMIT = -1;


CREATE DATABASE "parking-test"
WITH OWNER = parking
ENCODING = 'UTF8'
TABLESPACE = pg_default
LC_COLLATE = 'en_US.UTF-8'
LC_CTYPE = 'en_US.UTF-8'
CONNECTION LIMIT = -1;